project:
  type: website
  render:
    - index.qmd
    - notebooks/veteran-lung-cancer-overview.qmd
    - notebooks/veteran-lung-cancer-coxph-report.qmd

website:
  title: "Veteran Lung Cancer Survival Analysis"
  navbar:
    background: dark
    left:
      - href: index.qmd
        text: Home
      - href: notebooks/veteran-lung-cancer-overview.qmd
        text: Overview
      - href: notebooks/veteran-lung-cancer-coxph-report.qmd
        text: Report

format:
  html:
    theme:
      light: [cosmo, assets/styles.css]
      dark: [darkly, assets/styles-dark.css]
    toc: true
