{
  "hash": "8f663dd34c5e57588ce7387b8e65ba9b",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Survival Analysis: Veteran Lung Cancer Patients\"\nauthor: \"Julian Chung\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    number-sections: true\n    theme: cosmo\nexecute:\n  echo: true\n---\n# 📘 Introduction\n\nThis dataset originates from a clinical trial conducted by the Veterans Administration in the United States to compare the effectiveness of two chemotherapy regimens in treating advanced, inoperable lung cancer. Patients were randomized to receive either a standard treatment or a test treatment (an experimental chemotherapy protocol), and followed until death or censoring. The primary outcome was overall survival, measured in days from treatment initiation.\n\nThe dataset contains information on:\n\n    Treatment group (Standard vs Test),\n\n    Cell type (squamous, small cell, adenocarcinoma, or large cell),\n\n    Survival time and status,\n\n    Karnofsky performance score (a proxy for baseline health),\n\n    Time from diagnosis to study entry,\n\n    Patient age, and\n\n    Number of prior treatments received.\n\nThe data is widely used in survival analysis teaching due to its realistic structure, meaningful clinical context, and manageable size.\n\nD Kalbfleisch and RL Prentice (1980), The Statistical Analysis of Failure Time Data. Wiley, New York.\n\n# 📦 Load Packages\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(survival)\nlibrary(survminer)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: ggplot2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: ggpubr\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'survminer'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following object is masked from 'package:survival':\n\n    myeloma\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(dplyr)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'dplyr'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from 'package:stats':\n\n    filter, lag\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from 'package:base':\n\n    intersect, setdiff, setequal, union\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(broom)\nlibrary(splines)\n```\n:::\n\n\n# 🧬 Load & Inspect Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load the dataset\nveteran <- survival::veteran %>%\n  mutate(trt = factor(trt, levels = c(1, 2), labels = c(\"Control\", \"Intervention\")))\n\n# Peek at the structure and summary\nglimpse(veteran)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 137\nColumns: 8\n$ trt      <fct> Control, Control, Control, Control, Control, Control, Control…\n$ celltype <fct> squamous, squamous, squamous, squamous, squamous, squamous, s…\n$ time     <dbl> 72, 411, 228, 126, 118, 10, 82, 110, 314, 100, 42, 8, 144, 25…\n$ status   <dbl> 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0…\n$ karno    <dbl> 60, 70, 60, 60, 70, 20, 40, 80, 50, 70, 60, 40, 30, 80, 70, 6…\n$ diagtime <dbl> 7, 5, 3, 9, 11, 5, 10, 29, 18, 6, 4, 58, 4, 9, 11, 3, 9, 2, 4…\n$ age      <dbl> 69, 64, 38, 63, 65, 49, 69, 68, 43, 70, 81, 63, 63, 52, 48, 6…\n$ prior    <dbl> 0, 10, 0, 10, 10, 0, 10, 0, 0, 0, 0, 10, 0, 10, 10, 0, 0, 0, …\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(veteran)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           trt          celltype       time           status      \n Control     :69   squamous :35   Min.   :  1.0   Min.   :0.0000  \n Intervention:68   smallcell:48   1st Qu.: 25.0   1st Qu.:1.0000  \n                   adeno    :27   Median : 80.0   Median :1.0000  \n                   large    :27   Mean   :121.6   Mean   :0.9343  \n                                  3rd Qu.:144.0   3rd Qu.:1.0000  \n                                  Max.   :999.0   Max.   :1.0000  \n     karno          diagtime           age            prior      \n Min.   :10.00   Min.   : 1.000   Min.   :34.00   Min.   : 0.00  \n 1st Qu.:40.00   1st Qu.: 3.000   1st Qu.:51.00   1st Qu.: 0.00  \n Median :60.00   Median : 5.000   Median :62.00   Median : 0.00  \n Mean   :58.57   Mean   : 8.774   Mean   :58.31   Mean   : 2.92  \n 3rd Qu.:75.00   3rd Qu.:11.000   3rd Qu.:66.00   3rd Qu.:10.00  \n Max.   :99.00   Max.   :87.000   Max.   :81.00   Max.   :10.00  \n```\n\n\n:::\n:::\n\n\n# 📈 Kaplan-Meier Survival Curve\n\nFirstly we estimate the **survival function** for patients using the Kaplan-Meier estimator. This provides a non-parametric view of survival over time, stratified by treatment group.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create the survival object\nsurv_obj <- Surv(time = veteran$time, event = veteran$status)\n\n# Fit Kaplan-Meier curve stratified by treatment\nkm_fit <- survfit(surv_obj ~ trt, data = veteran)\n\n# View basic survival summary\nsummary(km_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall: survfit(formula = surv_obj ~ trt, data = veteran)\n\n                trt=Control \n time n.risk n.event survival std.err lower 95% CI upper 95% CI\n    3     69       1   0.9855  0.0144      0.95771        1.000\n    4     68       1   0.9710  0.0202      0.93223        1.000\n    7     67       1   0.9565  0.0246      0.90959        1.000\n    8     66       2   0.9275  0.0312      0.86834        0.991\n   10     64       2   0.8986  0.0363      0.83006        0.973\n   11     62       1   0.8841  0.0385      0.81165        0.963\n   12     61       2   0.8551  0.0424      0.77592        0.942\n   13     59       1   0.8406  0.0441      0.75849        0.932\n   16     58       1   0.8261  0.0456      0.74132        0.921\n   18     57       2   0.7971  0.0484      0.70764        0.898\n   20     55       1   0.7826  0.0497      0.69109        0.886\n   21     54       1   0.7681  0.0508      0.67472        0.874\n   22     53       1   0.7536  0.0519      0.65851        0.862\n   27     51       1   0.7388  0.0529      0.64208        0.850\n   30     50       1   0.7241  0.0539      0.62580        0.838\n   31     49       1   0.7093  0.0548      0.60967        0.825\n   35     48       1   0.6945  0.0556      0.59368        0.812\n   42     47       1   0.6797  0.0563      0.57782        0.800\n   51     46       1   0.6650  0.0570      0.56209        0.787\n   52     45       1   0.6502  0.0576      0.54649        0.774\n   54     44       2   0.6206  0.0587      0.51565        0.747\n   56     42       1   0.6059  0.0591      0.50040        0.734\n   59     41       1   0.5911  0.0595      0.48526        0.720\n   63     40       1   0.5763  0.0598      0.47023        0.706\n   72     39       1   0.5615  0.0601      0.45530        0.693\n   82     38       1   0.5467  0.0603      0.44049        0.679\n   92     37       1   0.5320  0.0604      0.42577        0.665\n   95     36       1   0.5172  0.0605      0.41116        0.651\n  100     34       1   0.5020  0.0606      0.39615        0.636\n  103     32       1   0.4863  0.0607      0.38070        0.621\n  105     31       1   0.4706  0.0608      0.36537        0.606\n  110     30       1   0.4549  0.0607      0.35018        0.591\n  117     29       2   0.4235  0.0605      0.32017        0.560\n  118     27       1   0.4079  0.0602      0.30537        0.545\n  122     26       1   0.3922  0.0599      0.29069        0.529\n  126     24       1   0.3758  0.0596      0.27542        0.513\n  132     23       1   0.3595  0.0592      0.26031        0.496\n  139     22       1   0.3432  0.0587      0.24535        0.480\n  143     21       1   0.3268  0.0582      0.23057        0.463\n  144     20       1   0.3105  0.0575      0.21595        0.446\n  151     19       1   0.2941  0.0568      0.20151        0.429\n  153     18       1   0.2778  0.0559      0.18725        0.412\n  156     17       1   0.2614  0.0550      0.17317        0.395\n  162     16       2   0.2288  0.0527      0.14563        0.359\n  177     14       1   0.2124  0.0514      0.13218        0.341\n  200     12       1   0.1947  0.0501      0.11761        0.322\n  216     11       1   0.1770  0.0486      0.10340        0.303\n  228     10       1   0.1593  0.0468      0.08956        0.283\n  250      9       1   0.1416  0.0448      0.07614        0.263\n  260      8       1   0.1239  0.0426      0.06318        0.243\n  278      7       1   0.1062  0.0400      0.05076        0.222\n  287      6       1   0.0885  0.0371      0.03896        0.201\n  314      5       1   0.0708  0.0336      0.02793        0.180\n  384      4       1   0.0531  0.0295      0.01788        0.158\n  392      3       1   0.0354  0.0244      0.00917        0.137\n  411      2       1   0.0177  0.0175      0.00256        0.123\n  553      1       1   0.0000     NaN           NA           NA\n\n                trt=Intervention \n time n.risk n.event survival std.err lower 95% CI upper 95% CI\n    1     68       2   0.9706  0.0205      0.93125        1.000\n    2     66       1   0.9559  0.0249      0.90830        1.000\n    7     65       2   0.9265  0.0317      0.86647        0.991\n    8     63       2   0.8971  0.0369      0.82766        0.972\n   13     61       1   0.8824  0.0391      0.80900        0.962\n   15     60       2   0.8529  0.0429      0.77278        0.941\n   18     58       1   0.8382  0.0447      0.75513        0.930\n   19     57       2   0.8088  0.0477      0.72056        0.908\n   20     55       1   0.7941  0.0490      0.70360        0.896\n   21     54       1   0.7794  0.0503      0.68684        0.884\n   24     53       2   0.7500  0.0525      0.65383        0.860\n   25     51       3   0.7059  0.0553      0.60548        0.823\n   29     48       1   0.6912  0.0560      0.58964        0.810\n   30     47       1   0.6765  0.0567      0.57394        0.797\n   31     46       1   0.6618  0.0574      0.55835        0.784\n   33     45       1   0.6471  0.0580      0.54289        0.771\n   36     44       1   0.6324  0.0585      0.52754        0.758\n   43     43       1   0.6176  0.0589      0.51230        0.745\n   44     42       1   0.6029  0.0593      0.49717        0.731\n   45     41       1   0.5882  0.0597      0.48216        0.718\n   48     40       1   0.5735  0.0600      0.46724        0.704\n   49     39       1   0.5588  0.0602      0.45244        0.690\n   51     38       2   0.5294  0.0605      0.42313        0.662\n   52     36       2   0.5000  0.0606      0.39423        0.634\n   53     34       1   0.4853  0.0606      0.37993        0.620\n   61     33       1   0.4706  0.0605      0.36573        0.606\n   73     32       1   0.4559  0.0604      0.35163        0.591\n   80     31       2   0.4265  0.0600      0.32373        0.562\n   84     28       1   0.4112  0.0597      0.30935        0.547\n   87     27       1   0.3960  0.0594      0.29509        0.531\n   90     25       1   0.3802  0.0591      0.28028        0.516\n   95     24       1   0.3643  0.0587      0.26560        0.500\n   99     23       2   0.3326  0.0578      0.23670        0.467\n  111     20       2   0.2994  0.0566      0.20673        0.434\n  112     18       1   0.2827  0.0558      0.19203        0.416\n  133     17       1   0.2661  0.0550      0.17754        0.399\n  140     16       1   0.2495  0.0540      0.16326        0.381\n  164     15       1   0.2329  0.0529      0.14920        0.363\n  186     14       1   0.2162  0.0517      0.13538        0.345\n  201     13       1   0.1996  0.0503      0.12181        0.327\n  231     12       1   0.1830  0.0488      0.10851        0.308\n  242     10       1   0.1647  0.0472      0.09389        0.289\n  283      9       1   0.1464  0.0454      0.07973        0.269\n  340      8       1   0.1281  0.0432      0.06609        0.248\n  357      7       1   0.1098  0.0407      0.05304        0.227\n  378      6       1   0.0915  0.0378      0.04067        0.206\n  389      5       1   0.0732  0.0344      0.02912        0.184\n  467      4       1   0.0549  0.0303      0.01861        0.162\n  587      3       1   0.0366  0.0251      0.00953        0.140\n  991      2       1   0.0183  0.0180      0.00265        0.126\n  999      1       1   0.0000     NaN           NA           NA\n```\n\n\n:::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Name the treatment groups\nveteran <- survival::veteran %>%\n  mutate(trt = factor(trt, \n                      levels = c(1, 2), \n                      labels = c(\"Control\", \"Intervention\")))\n\n# Create survival variable\nsurv_obj <- Surv(time = veteran$time, event = veteran$status)\n\n# Fit Kaplan-Meier model\nkm_fit <- survfit(surv_obj ~ trt, data = veteran)\n\n# Plot the KM curve\nggsurvplot(\n  km_fit,\n  data = veteran,\n  conf.int = TRUE,\n  pval = TRUE,\n  pval.size = 4,\n  risk.table = TRUE,\n  risk.table.title = \"Number at Risk\",\n  risk.table.col = \"strata\",\n  risk.table.y.text.col = TRUE,\n  risk.table.fontsize = 4,\n  legend.title = \"Treatment Group\",\n  legend.labs = c(\"Control\", \"Intervention\"),\n  xlab = \"Time (days)\",\n  ylab = \"Survival Probability\",\n  palette = c(\"#A569BD\", \"#45B39D\"),\n  title = \"Kaplan-Meier Survival Curve: VA Lung Cancer Trial\",\n  ggtheme = theme_minimal(base_size = 13) + \n    theme(\n      legend.position = \"top\",\n      plot.title = element_text(hjust = 0.5, face = \"bold\"),\n      panel.grid.major = element_line(color = \"grey80\", linewidth = 0.4),\n      panel.grid.minor = element_line(color = \"grey90\", linewidth = 0.2)\n    ),\n  tables.theme = theme(  # Trying to tweak the risk table\n    axis.text.y = element_text(size = 10, margin = margin(r = 12), lineheight = 2)\n  )\n)\n```\n\n::: {.cell-output-display}\n![](veteran-lung-cancer-coxph_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n### 🧠 Interpretation\n\nThe Kaplan-Meier plot shows survival curves for patients receiving standard vs test treatment.\n\n::: {.callout-note title=\"Interpretation of Graph Elements\" collapse=\"true\"}\n**X-Axis: Time (days)**\n\nThe X-axis shows the time since enrollment in days. The furthest value to the right (~1000 days) marks the maximum observed survival time in the dataset. Shorter durations towards the left reflect early mortality events. \n\n**Y-Axis: Survival Probability**\n\nThe Y-Axis is the Kaplan-Meier estimate of the probability that a patient survives beyond a certain timepoint. The axis starts at 1 (100% survival at time 0), and decreases with each event (death).\n\n**Curves (Blue = Standard, Orange = Test)**\n\nEach step downward represents a death. Tick marks would represent a censored individual (few in this dataset). \n\n**Shaded Area: 95% Confidence Interval** \n\nAround each curve is a shaded band indicating **uncertainty** in the estimate. Wider intervals to the right of the chart reflect fewer patients remaining and hence more variability in survival probability. \n\n**p = 0.93** \n\nThe log-rank test result tests the null hypothesis: there is no difference in survival between the groups. The p-value of 0.93 provides strong evidence _against_ rejecting the H0. In other words, there is no statistically significant difference in survival between the Standard and Test treatments. If the curves had diverged strongly at some point, the P-value would be lower. \n\n**\"Number at Risk\" Table**\n\nThis shows how many participatns in each treatment group are still alive and uncensored at various timepoints (0, 250, 500, 750, 1000). As time progresses the number declines due to deaths or censoring. Few participants remain beyond 500 days, which is why the Confidence Intervals widen later in the graph. \n\n- The **p-value** is from a log-rank test (H₀: no difference in survival curves).\n- The **shaded areas** represent 95% confidence intervals.\n- The **risk table** shows the number of patients still at risk at each time point.\n\nVisually, if the curves separate early and remain apart, it suggests a potential treatment effect.\n:::\n\n# 📊 Cox Proportional Hazards Model\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit the Cox Proportional Hazards model\ncox_model <- coxph(surv_obj ~ trt, data = veteran) # Where trt is a binary treatment variable with levels Control and Intervention\n\n# Summarize the model\nsummary(cox_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\ncoxph(formula = surv_obj ~ trt, data = veteran)\n\n  n= 137, number of events= 128 \n\n                   coef exp(coef) se(coef)     z Pr(>|z|)\ntrtIntervention 0.01774   1.01790  0.18066 0.098    0.922\n\n                exp(coef) exp(-coef) lower .95 upper .95\ntrtIntervention     1.018     0.9824    0.7144      1.45\n\nConcordance= 0.525  (se = 0.026 )\nLikelihood ratio test= 0.01  on 1 df,   p=0.9\nWald test            = 0.01  on 1 df,   p=0.9\nScore (logrank) test = 0.01  on 1 df,   p=0.9\n```\n\n\n:::\n:::\n\n\n::: {.callout-note title=\"Interpretation of Cox Table\" collapse=\"true\"}\n\n| Term          | Value          | What It Means                                                                                                                                                                         |\n| ------------- | -------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |\n| **coef**      | 0.01774        | This is the log hazard ratio (log(HR)) comparing the *Intervention* group to *Control*. Close to 0 means almost no effect.                                                            |\n| **exp(coef)** | 1.01790        | This is the hazard ratio (HR). A value of 1.018 means the hazard (risk of death) is 1.8% higher in the Intervention group compared to Control. However at this level the value is insigificant. |\n| **se(coef)**  | 0.18066        | The standard error. This gives us the variability around the estimate.                                                                                                                |\n| **z**         | 0.098          | The Wald test statistic. The low value implies no stastical significange.                                                                                     |\n| **p-value**   | 0.922          | Far above the conventional 0.05 threshold. This is very strong evidence *against* any meaningful treatment effect.                                                           |\n| **95% CI**    | (0.7144, 1.45) | Wide confidence interval, spanning both below and above 1—so we can't rule out either harm or benefit.                                                                                |\n**Concordance** The C-index, or concordance statistic is the probability that a candomly hosen subject who died earlier had a higher predicted risk. At 0.525 it is random chance, suggested poor predictive power. \n\n::: \n\n**Interpretation of the Cox Model Results**\n\nThe Cox proportional hazards model found no statistically significant difference in survival between the Control and Intervention groups (HR = 1.02, 95% CI: 0.71–1.45, p = 0.922). The hazard ratio close to 1 suggests that the treatment had no appreciable effect on the risk of death. Additionally, the wide confidence interval includes both potential harm and benefit, indicating uncertainty in the estimate. The concordance statistic (0.525) implies the model has poor discriminative ability, performing only slightly better than random chance. Overall, the analysis provides no evidence that the intervention improves survival outcomes in this dataset.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Use ggadjustedcurves for plotting adjusted survival curves directly from the Cox model\nggadjustedcurves(\n  cox_model,                     # The fitted Cox model\n  data = veteran,                # The original data used to fit the model\n  variable = \"trt\",              # The variable to plot adjusted curves for\n  method = \"average\",            # Method for adjusting (average effect of other covariates)\n  conf.int = TRUE,\n  legend.labs = c(\"Control\", \"Intervention\"),\n  legend.title = \"Treatment Group\",\n  risk.table = TRUE,             # Include the risk table\n  risk.table.title = \"Number at Risk\",\n  xlab = \"Time (days)\",\n  ylab = \"Adjusted Survival Probability\",\n  title = \"Cox Model Adjusted Survival Curves\",\n  palette = c(\"#A569BD\", \"#45B39D\"),\n  ggtheme = theme_minimal(base_size = 13) +\n    theme(\n      legend.position = \"top\",\n      plot.title = element_text(hjust = 0.5, face = \"bold\"),\n      panel.grid.major = element_line(color = \"grey80\", linewidth = 0.4),\n      panel.grid.minor = element_line(color = \"grey90\", linewidth = 0.2)\n    ),\n  tables.theme = theme(\n    axis.text.y = element_text(size = 10, margin = margin(r = 12), lineheight = 2)\n  )\n)\n```\n\n::: {.cell-output-display}\n![](veteran-lung-cancer-coxph_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n::: {.callout-tip title=\"Why use `ggadjustedcurves()` for this plot\" collapse=\"true\"}\nFor plotting survival curves adjusted for covariates from a Cox Proportional Hazards model, the ggadjustedcurves() function from the survminer package offers one of the most direct and statistically appropriate approaches—particularly as model complexity increases.\n\n    Statistical validity: ggadjustedcurves() uses the fitted cox_model to compute adjusted survival probabilities for the variable of interest (in this case, trt). When method = \"average\" is specified (the default when covariates are present), it returns marginal estimates—appropriate for interpreting average treatment effects across the population. In our simpler model (~ trt), it effectively plots the model-predicted survival curve for each treatment group.\n\n    Robustness: This function is purpose-built for adjusted curve plotting and avoids many of the pitfalls seen with manually passing newdata to survfit() and plotting with ggsurvplot(), such as misaligned strata or legend issues. It correctly associates the model, the data, and the plot elements, including the risk table.\n\n    Simplicity: It eliminates the need for manually constructing a new_trt data frame or calling survfit() separately, resulting in cleaner, more reproducible code—particularly useful in collaborative or long-term projects.\n:::\n\nThe Cox-adjusted survival curves for the Control and Intervention groups are almost perfectly overlapping, indicating no meaningful difference in predicted survival probabilities between the two treatment arms. This is consistent with the hazard ratio from the Cox model, which was very close to 1, and not statistically significant. Visually, the indistinguishability of the curves reinforces the conclusion that the treatment had no observable impact on survival in this dataset.\n\n::: {.callout-note title=\"Why do the lines overlap?\" collapse=\"true\"}\nThe survival curves for the Control and Intervention groups overlap almost entirely in this plot. This is because the Cox proportional hazards model found no significant difference between the two groups in terms of survival (hazard ratio ≈ 1, *p* = 0.922). As a result, the model-predicted curves are nearly identical. The faint visibility of the Control group line is due to it being directly behind the Intervention group line.\n:::\n\n# 🔎 Model Diagnostics\n\n## Checking the Proportional Hazards Assumption\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Test the PH assumption\ncox.zph(cox_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       chisq df    p\ntrt     3.54  1 0.06\nGLOBAL  3.54  1 0.06\n```\n\n\n:::\n:::\n\n\n**Interpretation of PH Assumption Test (Schoenfeld residuals)**\n\n- trt p = 0.06: This is slightly above the conventional threshold of 0.05. It suggest no strong evidence of violation of the proportional hazards (PH) assumptions for _treatment_. \n- GLOBAL p = 0.06: This tests the model overall. Not statistically significant so we do not reject the PH assumptions. \n\n**Porportional Hazards Assumption**\n\nThe proportional hazards assumption was assessed using Schoenfeld residuals via the cox.zph() function. The test for the treatment variable (trt) yielded a chi-square statistic of 3.54 with a p-value of 0.06, and the global test returned the same values (χ² = 3.54, df = 1, p = 0.06).\n\nAlthough the p-values are slightly above the conventional significance threshold of 0.05, they do not provide sufficient evidence to reject the null hypothesis that the proportional hazards assumption holds. As such, the Cox proportional hazards model is considered appropriate for this analysis, though the borderline result suggests caution and may warrant further inspection in more complex models.\n\n## Schoenfeld Residuals Plot\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(cox.zph(cox_model))\n```\n\n::: {.cell-output-display}\n![](veteran-lung-cancer-coxph_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n::: {.callout-note title=\"What the Visual Diagnostic Shows\" collapse=\"true\"}\n\nThe y-axis: Scaled Schoenfeld residuals for trt. If the proportional hazards assumption holds, these residuals should fluctuate randomly around zero.\n\nThe x-axis: Time (or transformed time).\n\nThe line: A smoothed spline fit (typically a loess curve) showing the trend of residuals over time.\n\nThe confidence band: Helps you assess whether the trend significantly deviates from horizontal (i.e., no time-dependent effect).\n\nA flat line (slope ≈ 0): Suggests the hazard ratio for trt does not change over time — good!\n\nA wavy or sloped line: Suggests potential violation of the proportional hazards assumption — this would back up a significant p-value.\n\nx-axis (Time): Time since baseline (likely in days, from your dataset).\n\ny-axis (Beta(t) for trt): Time-varying estimate of the log hazard ratio for the treatment group (trt), based on Schoenfeld residuals.\n\nThe solid black line: A smoothed curve showing how the estimated coefficient for trt might change over time.\n\nDashed lines: Approximate 95% confidence bands around that smoothed estimate.\n\nOpen circles: Residuals for each individual event — they don't need to follow a pattern, but their distribution can hint at model fit.\n\nIf the solid line is roughly flat and within the dashed lines, the effect of treatment does not change with time, and the PH assumption is reasonably upheld.\n\nIf the solid line drifts noticeably over time, or wanders outside the dashed lines, that's evidence that the treatment effect may change — a violation of the PH assumption.\n\nIn our case, the line is gently curved, but still well within the dashed boundaries. There's no strong time trend — the log hazard ratio is hovering around zero and doesn't appear to increase or decrease dramatically.\n\n:::\n\n**Schoenfeld Residuals Interpretation**\n\nTo assess whether the proportional hazards (PH) assumption holds for the treatment variable (trt), we examined Schoenfeld residuals using both statistical and graphical diagnostics. The global test for proportionality yielded a p-value of 0.06, indicating no statistically significant violation of the PH assumption at the conventional α = 0.05 level, though it approaches significance. The smoothed residual plot for trt shows a relatively stable trend over time, with the estimated log hazard ratio remaining within the 95% confidence bands across the follow-up period. While there is some minor curvature in the smoothed line, it does not suggest substantial deviation from proportionality. These findings support the use of the Cox proportional hazards model for analyzing the effect of treatment on survival in this dataset.\n\n## Martingale Residuals (for Functional Form of Covariates)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Generate Martingale residuals\nmartingale_resid <- residuals(cox_model, type = \"martingale\")\n\n# Add residuals to your data\nveteran$martingale <- martingale_resid\n\n# Plot residuals against a continuous covariate (e.g., time or another variable)\n# Here we plot against the linear predictor for simplicity\nveteran$linear_pred <- predict(cox_model, type = \"lp\")\n\nggplot(veteran, aes(x = linear_pred, y = martingale, color = trt)) +\n  geom_point(alpha = 0.6) +\n  geom_hline(yintercept = 0, linetype = \"dashed\", color = \"grey30\") +\n  theme_minimal(base_size = 13) +\n  labs(\n    title = \"Martingale Residuals vs Linear Predictor\",\n    x = \"Linear Predictor (Log Hazard)\",\n    y = \"Martingale Residual\",\n    color = \"Treatment Group\"\n  ) +\n  scale_color_manual(values = c(\"Control\" = \"#A569BD\", \"Intervention\" = \"#45B39D\")) +\n  theme(plot.title = element_text(hjust = 0.5, face = \"bold\"))\n```\n\n::: {.cell-output-display}\n![](veteran-lung-cancer-coxph_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n::: {.callout-note title=\"What do the Martingale Residuals Show\" collapse=\"true\"}\n\nMartingale residuals help us check whether the variables in our Cox model are specified correctly — particularly useful for continuous covariates. However, when the variable in question is binary (like our treatment group: Control vs Intervention), the Martingale residual plot will display two vertical stacks of points — one for each group.\n\nIn the plot above:\n\n- The **x-axis** represents the linear predictor (log hazard). Because the treatment is binary, there are only two unique predictor values: one for the control group and one for the intervention group.\n- The **y-axis** shows the Martingale residuals for each individual.\n- The **dashed horizontal line at 0** acts as a visual guide to see if residuals are randomly scattered above and below it.\n\nWe want to see:\n- No clear patterns or trends in the residuals,\n- A reasonably symmetric spread around zero in each group,\n- No outliers clustering far from the bulk of points.\n\nIn this case, both groups show a spread of residuals centered roughly around zero, with no curvature or skew that would suggest model misspecification. That's a good sign — the model's structure seems to handle the treatment variable well, and there's no obvious reason to suspect we need to transform it or add interaction terms.\n\n:::\n\nThe Martingale Residuals vs Linear Predictor plot helps us check the fit of our Cox model—specifically, whether our model's assumptions about the shape of relationships between predictors and survival are holding up.\n\nMartingale residuals were plotted against the linear predictor to assess model fit. As expected with a binary treatment variable, the plot showed two vertical bands of points corresponding to the Control and Intervention groups. The residuals appeared symmetrically distributed around zero within each group, with no obvious non-linear patterns or systematic bias. This suggests the model's functional form for the treatment variable is appropriate.\n\n## Functional Form of Covariates\n\n::: {.callout-tip title=\"Why we haven't checked the functional form of covariates\" collapse=\"true\"}\n\nThe Cox model assumes a linear relationship between continuous covariates and the log hazard. In our current model, only the treatment group (`trt`) is included, which is a categorical variable. \n\nIf we were to build a more complex model including continuous predictors like age, Karnofsky score (`karno`), or time since diagnosis (`diagtime`), we would need to assess whether their relationship with the log hazard is truly linear. This is typically done by plotting Martingale residuals or using `ggcoxfunctional()`.\n\nFor now, since our model does not include continuous covariates, this step is not necessary — but it's an important part of model diagnostics when expanding our analysis.\n\n:::\n\n## Additional Covariates\n\n# 🔀 Multivariable Cox Regression\n\nTo build on the univariable analysis of treatment effects, we next fit a multivariable Cox proportional hazards model that incorporates additional patient-level covariates. This allows us to estimate the effect of treatment on survival **while adjusting for other potential prognostic factors**, such as age and prior treatment history. By doing so, we account for potential confounding and improve the model's explanatory power.\n\n::: {.callout-tip title=\"What is a multivariable Cox model and why are we using it?\" collapse=\"true\"}\nIn a univariable Cox model, we examine the effect of **one predictor at a time** on the hazard of an event (e.g., death). While this can be useful for preliminary exploration, it doesn't account for the **influence of other variables** that might confound or modify the relationship.\n\nA **multivariable Cox proportional hazards model** includes **multiple covariates** simultaneously. This allows us to:\n- Estimate the **adjusted effect** of each variable while controlling for the others,\n- Improve model accuracy and interpretability,\n- Detect whether the apparent effect of one variable (e.g., treatment) persists after adjusting for others (e.g., age, comorbidities),\n- Explore potential **interactions** or **effect modification**.\n\nIn this section, we'll first add a **continuous covariate** (`age`) and then a **binary variable** (`prior treatment`) to the model. We'll also assess whether the functional form of continuous variables is appropriate and ensure that model assumptions still hold.\n:::\n\n::: {callout-tip title=\"Why not use logistic regression?\"}\nLogistic regression ignores time-to-event and censoring. When working with survival data, Cox models are preferred as they preserve the time structure and allow for censored cases.\n:::\n\n## 📥 Add Covariates (Age, Prior Treatment)\n\nTo expand the model beyond treatment alone, we now include additional patient characteristics: `age` (a continuous variable) and `prior` (indicating whether the patient received prior therapy, a binary variable). Including these covariates allows us to better account for baseline differences between patients, assess their independent associations with survival, and evaluate how these variables may influence the effect of treatment.\n\n::: {.callout-tip title=\"Why include more covariates?\" collapse=\"true\"}\n\nAdding additional covariates serves several important purposes in survival analysis:\n\n- **Control for confounding:** Variables like age and prior treatment may influence both survival and the likelihood of receiving a particular treatment. Including them helps isolate the true effect of treatment.\n- **Improve model accuracy:** Covariates that predict survival can increase the model's explanatory power and reduce residual variation.\n- **Uncover independent predictors:** Some variables (like prior therapy) may have a meaningful relationship with survival, regardless of treatment.\n- **Assess effect modification:** Once multiple variables are included, we can test for interactions — for example, whether the effect of treatment depends on age or prior treatment status.\n\nWe'll begin by examining `age` as a continuous covariate (with extra attention to its functional form), followed by `prior` as a binary covariate. We'll then combine them in a multivariable Cox model.\n\n:::\n\n### 🔁 Continuous Variable: Age\n\nAge is a clinically relevant factor that may influence survival outcomes in lung cancer. In this section, we assess whether age is independently associated with survival time and verify that its relationship with the hazard is appropriately modeled as linear on the log-hazard scale.\n\n::: {.callout-tip title=\"Why model age carefully?\" collapse=\"true\"}\nUnlike categorical variables, continuous predictors like age require us to check their **functional form** in the model. The Cox model assumes a **linear relationship** between the covariate and the log hazard — meaning each 1-year increase in age is assumed to have the same proportional effect on the hazard.\n\nIf this assumption doesn't hold (e.g., if risk increases faster at older ages), we may need to use transformations or splines to accurately model the relationship.\n\nWe'll start by fitting a Cox model including age and then assess the functional form using Martingale residuals.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncox_age <- coxph(Surv(time, status) ~ trt + age, data = veteran)\nsummary(cox_age)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\ncoxph(formula = Surv(time, status) ~ trt + age, data = veteran)\n\n  n= 137, number of events= 128 \n\n                     coef exp(coef)  se(coef)      z Pr(>|z|)\ntrtIntervention -0.003654  0.996352  0.182514 -0.020    0.984\nage              0.007527  1.007556  0.009661  0.779    0.436\n\n                exp(coef) exp(-coef) lower .95 upper .95\ntrtIntervention    0.9964     1.0037    0.6967     1.425\nage                1.0076     0.9925    0.9887     1.027\n\nConcordance= 0.514  (se = 0.029 )\nLikelihood ratio test= 0.63  on 2 df,   p=0.7\nWald test            = 0.62  on 2 df,   p=0.7\nScore (logrank) test = 0.62  on 2 df,   p=0.7\n```\n\n\n:::\n:::\n\n\nA Cox proportional hazards model was fitted to examine the relationship between survival time and two predictors: treatment group (trt) and patient age (age). The model included 137 patients, with 128 events (deaths).\n\nThe hazard ratio for the intervention group was 0.996 (95% CI: 0.697 – 1.425; p = 0.984), suggesting virtually no difference in hazard compared to the control group after adjusting for age. This effect was not statistically significant.\n\nFor age, the hazard ratio was 1.008 (95% CI: 0.989 – 1.027; p = 0.436), indicating that each additional year of age was associated with a 0.8% increase in the hazard of death. However, this association was also not statistically significant and the confidence interval included 1, suggesting uncertainty about the true effect.\n\nOverall, the model's ability to discriminate between patients with longer vs shorter survival times was weak, with a concordance index of 0.514 (where 0.5 = random chance). The global model statistics — including the likelihood ratio test, Wald test, and score test — were all non-significant (p = 0.7), indicating that neither variable added substantial predictive value to the model.\n\nInterpretation:\n\n    There is no evidence of a treatment effect after adjusting for age.\n\n    Age may have a small effect, but in this sample, it is not statistically or clinically meaningful.\n\n    The overall model performs poorly in predicting survival in this dataset.\n\n::: {.callout-note title=\"Interpreting the Cox Model Output\" collapse=\"true\"}\n\nUnderstanding the `coxph()` output is essential for interpreting survival models. Here's a breakdown of the most common components you'll encounter in both univariable and multivariable Cox regressions:\n\n**🔹 _coef_**  \nThis is the **log hazard ratio** — the raw estimate from the model. It represents the change in the **log hazard** of the event (e.g., death) associated with a **one-unit increase** in the covariate (for continuous variables) or **relative to a reference group** (for categorical variables).\n\n- Positive `coef` → increased hazard (i.e., higher risk)  \n- Negative `coef` → decreased hazard (i.e., protective)  \n- A `coef` close to 0 suggests little to no effect\n\n🧠 _Note:_ Log hazards are difficult to interpret directly, so we usually exponentiate them.\n\n**🔹 _exp(coef)_**  \nThis is the **hazard ratio (HR)** — the exponentiated `coef`, which expresses effect size more intuitively.\n\n- `exp(coef) > 1` → Increased hazard  \n- `exp(coef) < 1` → Decreased hazard  \n- `exp(coef) = 1` → No effect\n\n🔎 Example: `exp(coef) = 1.20` means a 20% higher hazard.  \n`exp(coef) = 0.80` means a 20% lower hazard.\n\n**🔹 _se(coef)_**  \nThe **standard error** of the coefficient — reflects how much uncertainty surrounds the estimate.\n\n- Smaller values = more precise estimates  \n- Larger values = more uncertainty (due to small samples or noisy data)\n\n**🔹 _z_ and _Pr(>|z|)_**  \n- `z` is the **Z-statistic**, calculated as `coef / se(coef)`  \n- `Pr(>|z|)` is the **p-value** from the Wald test for each coefficient\n\nThis tests the **null hypothesis** that the covariate has **no effect** (`coef = 0`).\n\n- `p < 0.05` → Statistically significant  \n- `p > 0.05` → Not statistically significant\n\n**📊 _Model-Level Statistics_**\n\n**🔸 _Concordance_**  \n- Measures the model's ability to correctly rank survival times (similar to AUC for classification)  \n- Ranges from `0.5` (random) to `1.0` (perfect)  \n- In clinical data, values of `0.6–0.75` are typical\n\n**🔸 _Likelihood Ratio Test_**  \n- Compares the full model to a null (intercept-only) model  \n- Tests overall model fit  \n- `p < 0.05` = your model significantly improves fit\n\n**🔸 _Wald Test_**  \n- Aggregates the individual Wald tests across all covariates  \n- Tests whether any coefficients differ significantly from 0\n\n**🔸 _Score (Logrank) Test_**  \n- Rank-based test comparing observed vs expected survival  \n- Can be slightly more sensitive in small samples  \n- Often used as an overall model check\n\n✅ _In practice:_ Use all three global tests and the concordance to evaluate how well the model explains variation in survival. If all are non-significant, the model may lack predictive utility.\n\n:::\n\n\n**📈 Schoenfeld Residuals for Age**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Test proportional hazards assumption for the model including age\ncox_zph_age <- cox.zph(cox_age)\nprint(cox_zph_age)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       chisq df     p\ntrt     3.67  1 0.055\nage     1.68  1 0.195\nGLOBAL  6.20  2 0.045\n```\n\n\n:::\n:::\n\n\nProportional hazards were tested using Schoenfeld residuals. The assumption was met for **age** (`p = 0.195`) but marginally violated for **treatment group** (`p = 0.055`), which is slightly below the conventional threshold of 0.05. The **global test** for the model (`p = 0.045`) was also just below 0.05, indicating a **possible overall violation** of the proportional hazards assumption.\n\nWhile these results do not strongly indicate a breakdown of the PH assumption, the borderline p-values warrant caution. A visual inspection of the residual plots (`plot(cox.zph())`) can help determine whether the trend is substantial or random variation.\n\n::: {.callout-note title=\"Interpreting Schoenfeld Residuals\" collapse=\"true\"}\n\nSchoenfeld residuals are used to test the **Proportional Hazards (PH) assumption** in Cox models — that the effect of each covariate remains **constant over time**.\n\n**How to interpret the output:**\n\n- Each row (e.g., `trt`, `age`) gives a **test of proportionality** for that specific variable.\n- The `GLOBAL` row tests **all covariates together**.\n\n**What the numbers mean:**\n\n- `chisq` is the test statistic (larger values = more evidence of time-varying effects).\n- `p` is the p-value testing **null hypothesis: proportional hazards holds**.\n\n**Rule of thumb:**\n- `p < 0.05` → **PH assumption violated** (bad)\n- `p > 0.05` → **PH assumption holds** (good)\n\n🧠 _Note:_ Slight violations (e.g., `p = 0.055`) might not be a problem in practice — but major ones (e.g., `p = 0.01`) should be addressed.\n\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Visual check\nplot(cox_zph_age)\n```\n\n::: {.cell-output-display}\n![](veteran-lung-cancer-coxph_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](veteran-lung-cancer-coxph_files/figure-html/unnamed-chunk-12-2.png){width=672}\n:::\n:::\n\n\nThe Schoenfeld residual plot for age demonstrated no clear violations of the proportional hazards assumption. The smoothed coefficient function remained approximately flat across time, and the 95% confidence interval consistently included zero. This visual finding supports the conclusion from the formal test (`p = 0.195`), suggesting that the effect of age on the hazard is relatively stable over the study period.\n\n::: {.callout-note title=\"How to Interpret Schoenfeld Residual Plots\" collapse=\"true\"}\n\nThis plot checks the **Proportional Hazards (PH) assumption** visually for a covariate (e.g., `age`).\n\n**What we are seeing:**\n\n- **X-axis:** Time  \n- **Y-axis:** Estimated **effect (beta)** of the covariate at each time point  \n- **Dots:** Residuals at each event time  \n- **Solid line:** Smoothed trend of the coefficient over time  \n- **Dashed lines:** 95% confidence interval of that trend  \n\n**What we want to see:**\n\n✅ A **flat line near zero**, with the confidence band **containing zero** throughout time → suggests **PH assumption holds**.\n\n⚠️ A **wavy trend** or curve **drifting far from zero** → suggests **non-proportional hazards** (i.e., the effect of the covariate changes over time).\n\n**Interpreting the plot:**\n\nIf the smoothed line is approximately flat and the confidence interval consistently includes zero — with no strong patterns or directional trends — then the PH assumption is likely satisfied for that covariate.\n\n:::\n\n**📈 Martingale Residuals for Age to Assess Functional Form**\n\nTo assess whether age is appropriately modeled as a linear predictor in the Cox model, we examine Martingale residuals plotted against age to detect non-linearity in its functional form.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Generate Martingale residuals\nveteran$martingale_age <- residuals(cox_age, type = \"martingale\")\n\n# Generate linear predictor\nveteran$linear_pred_age <- predict(cox_age, type = \"lp\")\n\n# Plot residuals against age\nggplot(veteran, aes(x = age, y = martingale_age, color = trt)) +\n  geom_point(alpha = 0.6) +\n  geom_hline(yintercept = 0, linetype = \"dashed\", color = \"grey30\") +\n  theme_minimal(base_size = 13) +\n  labs(\n    title = \"Martingale Residuals vs Age\",\n    x = \"Age (years)\",\n    y = \"Martingale Residual\",\n    color = \"Treatment Group\"\n  ) +\n  scale_color_manual(values = c(\"Control\" = \"#A569BD\", \"Intervention\" = \"#45B39D\")) +\n  theme(plot.title = element_text(hjust = 0.5, face = \"bold\"))\n```\n\n::: {.cell-output-display}\n![](veteran-lung-cancer-coxph_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\nMartingale residuals plotted against age showed no clear non-linear trend, with residuals generally scattered randomly across the range of age values. This suggests that modeling age as a linear term in the Cox model is reasonable. There is no strong evidence to support the need for transformations or spline-based modeling of age in this dataset.\n\n::: {.callout-note title=\"How to Interpret Martingale Residuals for Functional Form\" collapse=\"true\"}\n\nThis plot helps assess whether the **relationship between a continuous variable** (like _age_) and the **log hazard** is **linear**, which is a core assumption of the Cox model.\n\n- **X-axis:** The covariate\n- **Y-axis:** Martingale residuals (bounded between -∞ and 1)\n- **Points:** One per individual, representing how well their survival time is predicted\n- **Dashed line at 0:** Reference line to help spot patterns\n\n**What to look for:**\n- A **random scatter** of points across the X-axis with **no clear curve** → linearity assumption is likely satisfied ✅\n- A **systematic curve**, bend, or wave → suggests the effect of age might be **non-linear** ⚠️  \n  In that case, consider modeling age using splines or transformations (e.g., `log()` or `^2`).\n\n**Important:** These residuals are noisier near their bounds and should be interpreted cautiously, especially when sample size is limited.\n\n:::\n\n**📈 Functional Form Check**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit a univariable Cox model to assess functional form of age\ncox_age_only <- coxph(Surv(time, status) ~ age, data = veteran)\n\n# Check the functional form visually using Martingale residuals\nggcoxfunctional(cox_age_only, data = veteran)\n```\n\n::: {.cell-output-display}\n![](veteran-lung-cancer-coxph_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\n\n::: {.callout-note title=\"Assessing Functional Form with Martingale Residuals\" collapse=\"true\"}\n\n**What this plot shows:**  \nThis diagnostic visualizes whether a **continuous covariate** (e.g., _age_) has a **linear relationship** with the **log hazard**, as assumed by the Cox model.\n\n**X-axis:**  \nThe values of the continuous variable being assessed (e.g., age)\n\n**Y-axis:**  \nThe **Martingale residuals** from a **null Cox model** (i.e., a model with no covariates)\n\n**Dots:**  \nEach dot represents one observation\n\n**Smooth black line:**  \nA **non-parametric smoother** that helps reveal trends in the residuals — this is the key to checking the shape of the relationship\n\n**How to interpret it:**\n\n- ✅ If the **black line is roughly straight and flat**, this suggests a **linear relationship** between the variable and the log hazard — which is **what the Cox model assumes**.\n- ⚠️ If the line shows a **curved or non-linear pattern**, this suggests the variable may not be appropriately modeled with a simple linear term.  \n    - This can indicate the need to use **transformations** (e.g., `log(age)`, `age^2`) or **splines**.\n\n**Tip:**  \nSmall wobbles are not a major concern — we are primarily looking for clear trends, not minor bumps. Major **U-shapes, inflections, or long curves** are the most concerning signs.\n\n:::\n\nThe functional form check using Martingale residuals and a non-parametric smoother suggests that age may not have a strictly linear relationship with the log hazard. The smooth curve appears U-shaped, implying that risk may not increase evenly with age across the full range. This indicates that the assumption of linearity may be violated, and that alternative modeling strategies (e.g., polynomial terms or splines) could improve model fit.\n\nWhile the Martingale residual plot suggests that the relationship between age and the log hazard may not be strictly linear, age was not statistically significant in the model. As such, no transformation or spline was applied. This could be revisited in future modeling if age becomes more influential.\n\n### 🔁 Binary Variable: Prior Treatment\n\nWe now evaluate the variable `prior`, which indicates whether a patient received prior therapy before enrolment in the study. This binary variable may capture important differences in disease severity, treatment history, or prognosis that could influence survival outcomes.\n\n::: {.callout-tip title=\"Why test binary covariates like 'prior'?\" collapse=\"true\"}\nEven though `prior` is binary, its inclusion allows us to control for historical differences in patient treatment, which may affect survival independently of the trial treatment (`trt`). \n\nFor binary variables, we don't need to assess the functional form, but we **do need to check the proportional hazards assumption** (as with any covariate in the Cox model). We'll interpret the hazard ratio as the relative difference in risk between those who received prior therapy and those who did not.\n:::\n\n#### Fit Cox Model with Prior Treatment\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit the Cox model including prior treatment\ncox_prior <- coxph(Surv(time, status) ~ trt + prior, data = veteran)\nsummary(cox_prior)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\ncoxph(formula = Surv(time, status) ~ trt + prior, data = veteran)\n\n  n= 137, number of events= 128 \n\n                    coef exp(coef) se(coef)      z Pr(>|z|)\ntrtIntervention  0.02608   1.02643  0.18099  0.144    0.885\nprior           -0.01447   0.98563  0.02009 -0.720    0.471\n\n                exp(coef) exp(-coef) lower .95 upper .95\ntrtIntervention    1.0264     0.9743    0.7199     1.463\nprior              0.9856     1.0146    0.9476     1.025\n\nConcordance= 0.517  (se = 0.03 )\nLikelihood ratio test= 0.54  on 2 df,   p=0.8\nWald test            = 0.53  on 2 df,   p=0.8\nScore (logrank) test = 0.53  on 2 df,   p=0.8\n```\n\n\n:::\n:::\n\n\nA Cox proportional hazards model was fitted to evaluate the association between survival and two predictors: treatment group (trt) and prior therapy (prior). The model was based on 137 patients, with 128 observed events.\n\nThe hazard ratio for the intervention group was 1.03 (95% CI: 0.72 – 1.46, p = 0.885), indicating no evidence of a treatment effect after adjusting for prior therapy. Similarly, prior therapy was not associated with survival, with a hazard ratio of 0.99 (95% CI: 0.95 – 1.03, p = 0.471).\n\nModel discrimination was weak, with a concordance of 0.517, suggesting the model has limited ability to rank survival times accurately. Global model fit tests (likelihood ratio, Wald, and score) were all non-significant (p = 0.8), indicating that the included variables do not significantly improve model performance.\n\nNeither treatment assignment nor prior therapy appear to be meaningful predictors of survival in this dataset. There is no evidence of an additive effect between these covariates.\n\n***📈 Schoenfeld Residuals for Prior Treatment**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Test proportional hazards assumption for the model including prior treatment\ncox_zph_prior <- cox.zph(cox_prior)\nprint(cox_zph_prior)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       chisq df     p\ntrt     3.38  1 0.066\nprior   3.04  1 0.081\nGLOBAL  6.06  2 0.048\n```\n\n\n:::\n:::\n\n\nProportional hazards were assessed using Schoenfeld residuals for the model including treatment group and prior therapy. The global test was statistically significant (p = 0.048), suggesting potential violation of the proportional hazards assumption overall.\n\nIndividually, both treatment (p = 0.066) and prior therapy (p = 0.081) had p-values slightly above the conventional 0.05 threshold, indicating borderline evidence of non-proportionality. These results do not strongly confirm a violation, but they do warrant cautious interpretation.\n\nGiven the marginal nature of these findings, visual inspection of the Schoenfeld residual plots is recommended to assess whether any systematic time-varying effects are present.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Visual check\nplot(cox_zph_prior)\n```\n\n::: {.cell-output-display}\n![](veteran-lung-cancer-coxph_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](veteran-lung-cancer-coxph_files/figure-html/unnamed-chunk-17-2.png){width=672}\n:::\n:::\n\n\nThe Schoenfeld residual plot for prior reveals a largely flat smoothed line that stays within the 95% confidence band across time. While the global test for proportional hazards was statistically significant (p = 0.048), the visual inspection for prior shows no major deviation or time-varying effect. This supports the idea that, despite the borderline p-values, the proportional hazards assumption is reasonably met for the prior variable.\n\n**📈 Martingale Residuals for Prior Treatment**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Generate Martingale residuals\nveteran$martingale_prior <- residuals(cox_prior, type = \"martingale\")\n# Generate linear predictor\nveteran$linear_pred_prior <- predict(cox_prior, type = \"lp\")\n# Plot residuals against prior treatment\nggplot(veteran, aes(x = prior, y = martingale_prior, color = trt)) +\n  geom_point(alpha = 0.6) +\n  geom_hline(yintercept = 0, linetype = \"dashed\", color = \"grey30\") +\n  theme_minimal(base_size = 13) +\n  labs(\n    title = \"Martingale Residuals vs Prior Treatment\",\n    x = \"Prior Treatment (0 = No, 1 = Yes)\",\n    y = \"Martingale Residual\",\n    color = \"Treatment Group\"\n  ) +\n  scale_color_manual(values = c(\"Control\" = \"#A569BD\", \"Intervention\" = \"#45B39D\")) +\n  theme(plot.title = element_text(hjust = 0.5, face = \"bold\")) +\n  geom_point(position = position_jitter(width = 0.1), alpha = 0.6) # Adding jitter to avoid overlap\n```\n\n::: {.cell-output-display}\n![](veteran-lung-cancer-coxph_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\nThe Martingale residual plot for the prior variable shows two distinct clusters of points at 0 and 1, corresponding to patients with and without prior treatment, respectively. The residuals appear to be roughly symmetric around zero in both groups, with no strong indication of skew or heteroscedasticity. This supports the appropriateness of modeling prior as a binary variable in the Cox regression model. No transformation or alternative coding appears necessary.\n\n### 🔁 Multivariable Cox Model with Age and Prior Treatment\n\nIn this section, we fit a multivariable Cox proportional hazards model that includes both age and prior treatment as covariates. This allows us to assess the independent effects of these variables on survival while controlling for treatment group.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit the multivariable Cox model including age and prior treatment\ncox_multivariable <- coxph(Surv(time, status) ~ trt + age + prior, data = veteran)\nsummary(cox_multivariable)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\ncoxph(formula = Surv(time, status) ~ trt + age + prior, data = veteran)\n\n  n= 137, number of events= 128 \n\n                     coef exp(coef)  se(coef)      z Pr(>|z|)\ntrtIntervention  0.003621  1.003628  0.183151  0.020    0.984\nage              0.007124  1.007149  0.009675  0.736    0.462\nprior           -0.013562  0.986529  0.020118 -0.674    0.500\n\n                exp(coef) exp(-coef) lower .95 upper .95\ntrtIntervention    1.0036     0.9964    0.7009     1.437\nage                1.0071     0.9929    0.9882     1.026\nprior              0.9865     1.0137    0.9484     1.026\n\nConcordance= 0.507  (se = 0.03 )\nLikelihood ratio test= 1.09  on 3 df,   p=0.8\nWald test            = 1.07  on 3 df,   p=0.8\nScore (logrank) test = 1.07  on 3 df,   p=0.8\n```\n\n\n:::\n:::\n\n\n::: {.callout-note title=\"Interpreting the Cox Model Output\" collapse=\"true\"}\n\nUnderstanding the `coxph()` output is essential for interpreting survival models. Here's a breakdown of the most common components you'll encounter in both univariable and multivariable Cox regressions:\n\n**🔹 _coef_**  \nThis is the **log hazard ratio** — the raw estimate from the model. It represents the change in the **log hazard** of the event (e.g., death) associated with a **one-unit increase** in the covariate (for continuous variables) or **relative to a reference group** (for categorical variables).\n\n- Positive `coef` → increased hazard (i.e., higher risk)  \n- Negative `coef` → decreased hazard (i.e., protective)  \n- A `coef` close to 0 suggests little to no effect\n\n🧠 _Note:_ Log hazards are difficult to interpret directly, so we usually exponentiate them.\n\n**🔹 _exp(coef)_**  \nThis is the **hazard ratio (HR)** — the exponentiated `coef`, which expresses effect size more intuitively.\n\n- `exp(coef) > 1` → Increased hazard  \n- `exp(coef) < 1` → Decreased hazard  \n- `exp(coef) = 1` → No effect\n\n🔎 Example: `exp(coef) = 1.20` means a 20% higher hazard.  \n`exp(coef) = 0.80` means a 20% lower hazard.\n\n**🔹 _se(coef)_**  \nThe **standard error** of the coefficient — reflects how much uncertainty surrounds the estimate.\n\n- Smaller values = more precise estimates  \n- Larger values = more uncertainty (due to small samples or noisy data)\n\n**🔹 _z_ and _Pr(>|z|)_**  \n- `z` is the **Z-statistic**, calculated as `coef / se(coef)`  \n- `Pr(>|z|)` is the **p-value** from the Wald test for each coefficient\n\nThis tests the **null hypothesis** that the covariate has **no effect** (`coef = 0`).\n\n- `p < 0.05` → Statistically significant  \n- `p > 0.05` → Not statistically significant\n\n**📊 _Model-Level Statistics_**\n\n**🔸 _Concordance_**  \n- Measures the model's ability to correctly rank survival times (similar to AUC for classification)  \n- Ranges from `0.5` (random) to `1.0` (perfect)  \n- In clinical data, values of `0.6–0.75` are typical\n\n**🔸 _Likelihood Ratio Test_**  \n- Compares the full model to a null (intercept-only) model  \n- Tests overall model fit  \n- `p < 0.05` = your model significantly improves fit\n\n**🔸 _Wald Test_**  \n- Aggregates the individual Wald tests across all covariates  \n- Tests whether any coefficients differ significantly from 0\n\n**🔸 _Score (Logrank) Test_**  \n- Rank-based test comparing observed vs expected survival  \n- Can be slightly more sensitive in small samples  \n- Often used as an overall model check\n\n✅ _In practice:_ Use all three global tests and the concordance to evaluate how well the model explains variation in survival. If all are non-significant, the model may lack predictive utility.\n\n:::\n\n\nA multivariable Cox proportional hazards model was fitted to examine the association between survival and three covariates: treatment group, age, and prior therapy. After adjusting for all covariates:\n\n    The hazard ratio for the intervention group relative to control was 1.00 (HR = 1.00; 95% CI: 0.70–1.44; p = 0.984), indicating no evidence of a treatment effect.\n\n    Age had a hazard ratio of 1.01 per year (p = 0.462), suggesting no significant association with survival in this model.\n\n    Prior therapy also showed no effect on hazard (HR = 0.99; p = 0.500).\n\nModel discrimination was minimal (concordance = 0.507), and all global model tests were non-significant (p = 0.8), suggesting the model does not meaningfully predict survival in this dataset.\n\n**📈 Schoenfeld Residuals for Multivariable Model**\n\nWe now assess whether the **proportional hazards assumption** holds for each covariate in the multivariable Cox model. This step ensures that the effect of each variable — treatment group, age, and prior therapy — is consistent over time.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Test proportional hazards assumption for the multivariable model\ncox_zph_multivariable <- cox.zph(cox_multivariable)\nprint(cox_zph_multivariable)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       chisq df     p\ntrt     3.53  1 0.060\nage     1.76  1 0.184\nprior   3.19  1 0.074\nGLOBAL  8.80  3 0.032\n```\n\n\n:::\n:::\n\n\nThe proportional hazards assumption was assessed for the multivariable Cox model using Schoenfeld residuals. The global test was statistically significant (p = 0.032), suggesting that at least one covariate may have a time-varying effect on the hazard.\n\nAt the individual variable level:\n\n    trt showed borderline evidence of non-proportionality (p = 0.060)\n\n    prior also approached significance (p = 0.074)\n\n    age did not show evidence of time-varying effects (p = 0.184)\n\nWhile none of the individual tests crossed the 0.05 threshold, the cumulative result (GLOBAL p < 0.05) suggests some caution is warranted. Visual inspection of the Schoenfeld residual plots is recommended to evaluate whether these borderline findings correspond to meaningful deviations over time.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Visual check\nplot(cox_zph_multivariable)\n```\n\n::: {.cell-output-display}\n![](veteran-lung-cancer-coxph_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](veteran-lung-cancer-coxph_files/figure-html/unnamed-chunk-21-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](veteran-lung-cancer-coxph_files/figure-html/unnamed-chunk-21-3.png){width=672}\n:::\n:::\n\n\nVisual inspection of the Schoenfeld residual plot for the prior variable showed a relatively flat trend line with confidence intervals consistently containing zero. This suggests that the effect of prior treatment on the hazard is approximately constant over time, supporting the proportional hazards assumption for this covariate despite its borderline p-value in the global test.\n\n**Martingale Residuals for Multivariable Model**\n\nWe now examine the Martingale residuals from the multivariable Cox model to evaluate the overall model fit and identify any patterns or potential outliers in the covariate effects.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Generate Martingale residuals\nveteran$martingale_multivariable <- residuals(cox_multivariable, type = \"martingale\")\n# Generate linear predictor\nveteran$linear_pred_multivariable <- predict(cox_multivariable, type = \"lp\")\n# Plot residuals against linear predictor\nggplot(veteran, aes(x = linear_pred_multivariable, y = martingale_multivariable, color = trt)) +\n  geom_point(alpha = 0.6) +\n  geom_hline(yintercept = 0, linetype = \"dashed\", color = \"grey30\") +\n  theme_minimal(base_size = 13) +\n  labs(\n    title = \"Martingale Residuals vs Linear Predictor\\n(Multivariable Model)\",\n    x = \"Linear Predictor (Log Hazard)\",\n    y = \"Martingale Residual\",\n    color = \"Treatment Group\"\n  ) +\n  scale_color_manual(values = c(\"Control\" = \"#A569BD\", \"Intervention\" = \"#45B39D\")) +\n  theme(plot.title = element_text(hjust = 0.5, face = \"bold\"))\n```\n\n::: {.cell-output-display}\n![](veteran-lung-cancer-coxph_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\nThe Martingale residuals plotted against the linear predictor for the multivariable model appear randomly scattered around the horizontal zero line, with no clear pattern, curvature, or systematic deviation. This suggests that the overall functional form of the covariates (treatment, age, and prior treatment) is reasonably specified. There is no strong evidence of model misspecification or non-linearity in the combined effects. However, the narrow spread of the linear predictor values (mostly between -0.2 and 0.2) reflects the modest effect sizes and limited variation in the log hazard estimates, which aligns with the model's lack of significant predictors.\n\n::: {.callout-tip title=\"What This Plot Tells Us\" collapse=\"true\"}\n\nMartingale residuals help assess how well the Cox model fits the data.\n\nA good model will show residuals scattered symmetrically around zero with no systematic pattern.\n\nSince we are plotting residuals against the linear predictor (the model's estimate of log hazard for each individual), this acts as a catch-all for checking overall model specification.\n\nIn this case:\n\n- There's no strong non-linear trend.\n- No excessive clustering or heteroskedasticity.\n- Values are distributed fairly evenly above and below the zero line.\n\nConclusion: The model appears reasonably well-specified, and no major violations are detected.\n\n:::\n\n**Functional Form Check for Continuous Covariates**\n\nWe now recheck the functional form of the continuous variable age within the multivariable Cox model to ensure its effect on the log hazard remains appropriately modeled as linear.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Refit a univariable model with age (again, for functional form check)\ncox_age_for_form_check <- coxph(Surv(time, status) ~ age, data = veteran)\n\n# Plot functional form using ggcoxfunctional\nggcoxfunctional(\n  fit = cox_age_for_form_check,\n  data = veteran,\n  point.col = \"#E74C3C\",\n  ggtheme = theme_minimal(base_size = 13),\n  title = \"Functional Form Check: Age\"\n)\n```\n\n::: {.cell-output-display}\n![](veteran-lung-cancer-coxph_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\nThe Martingale residual plot for age reveals a clear U-shaped curve, suggesting that the assumption of linearity in the log hazard may not hold. This implies that age may have a non-linear effect on survival, and modeling it as a simple linear term may lead to misestimation of its effect. A transformation (e.g., quadratic or restricted cubic splines) may be warranted in further analysis.\n\n::: {.callout-tip title=\"Why Check Functional Form Again in a Multivariable Model?\" collapse=\"true\"}\n\nWhile functional form checks (e.g., using Martingale residuals) are **only necessary for continuous covariates**, it's important to **reassess them in the context of the full model** — even if they passed in a univariable setting.\n\n- In a **univariable Cox model**, we check whether the continuous variable (e.g., age) has a linear relationship with the log hazard.\n- However, once we add other covariates (like treatment or prior therapy), the relationship can **change due to confounding or interactions**.\n- A variable might look linear on its own, but **show non-linearity when adjusted** for other predictors.\n\nSo we recheck **only the continuous variables** (e.g., age) in the multivariable model to ensure the assumption still holds.\n\n:::\n\n## Multivariable Cox Model with Spline-Transformed Age\n\nWe refit the Cox model using a restricted cubic spline to model the non-linear relationship between age and the log hazard. This allows for greater flexibility in capturing age-related risk while still accounting for treatment and prior therapy.\n\n::: {.callout-note title=\"Understanding Spline and Non-Linear Transformations in Survival Models\" collapse=\"true\"}\n\n**Why model transformations at all?**  \nThe Cox Proportional Hazards model assumes that each covariate has a **linear relationship** with the **log hazard**. For **continuous variables** like age, this means that each one-unit increase is expected to have the same multiplicative effect on the hazard — *regardless of whether someone is 40 or 80 years old*. This is often unrealistic.\n\nTo fix this, we apply **non-linear transformations** to more accurately capture the shape of the relationship between a variable (like age) and the outcome (e.g., death).\n\n**What are spline transformations?**  \nSplines are a **flexible way to model non-linear relationships** without explicitly specifying the form of the curve. They break a variable into *segments* using predefined cut points called **knots**, and fit separate curves (usually polynomials) between them, ensuring smoothness at the joins.\n\nThey allow the model to \"bend\" as needed — making them perfect for capturing complex patterns in the data.\n\n**Common types of transformations:**\n\n**• _Restricted Cubic Splines (Natural Splines)_:**  \nThis is the most common spline in Cox models. It creates piecewise cubic polynomials between knots, but constrains the ends to be linear — which prevents overfitting at the tails.\n\n- ✅ Best for *flexible yet stable* curve fitting  \n- 📌 Recommended when you suspect non-linearity but don't want to manually test transformations\n\n**• _Quadratic or Polynomial Terms (e.g., age + I(age^2))_:**  \nAdds a squared (or cubic) term to capture curvature.\n\n- ✅ Simple to interpret\n- ⚠️ Risky at the extremes — can overfit or behave erratically\n\n**• _Log Transformations (e.g., log(age))_:**  \nUsed when the effect *decelerates* — i.e., rapid effect early on that flattens with increasing value.\n\n- ✅ Great when data is skewed\n- ⚠️ Doesn't work if the variable contains 0s or negatives\n\n**• _Categorization (e.g., age groups)_:**  \nTurns a continuous variable into bins (e.g., under 50, 50–65, over 65).\n\n- ✅ Easy to explain\n- ⚠️ Loses statistical power and may mislead if cutoffs are arbitrary\n\n**When should you use each?**\n\n| Transformation       | Use when...                                      |\n|----------------------|--------------------------------------------------|\n| **Splines (ns())**   | You want a smooth, data-driven relationship      |\n| **Quadratic term**   | You suspect a simple \"U-shaped\" or curvilinear trend |\n| **Log transform**    | The variable increases rapidly then levels off   |\n| **Categories**       | Clinical guidelines or reporting require it      |\n\n**How many knots do I use for splines?**  \nA good rule of thumb (Harrell, 2015):\n\n- 3 knots: small datasets (n < 100)\n- 4–5 knots: medium datasets (n ~ 100–300)\n- 5–7 knots: large datasets\n\nKnots are often placed at **percentiles** of the variable — e.g., 5th, 35th, 65th, 95th percentile.\n\nFinal tip: Always re-check Schoenfeld residuals and Martingale residuals after applying any transformation.\n\n:::\n\n**Model Output**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit a Cox model with restricted cubic splines for age\ncox_spline <- coxph(Surv(time, status) ~ ns(age, df = 3) + trt + prior, data = veteran)\nsummary(cox_spline)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\ncoxph(formula = Surv(time, status) ~ ns(age, df = 3) + trt + \n    prior, data = veteran)\n\n  n= 137, number of events= 128 \n\n                      coef exp(coef)  se(coef)      z Pr(>|z|)\nns(age, df = 3)1  0.039605  1.040400  0.336973  0.118    0.906\nns(age, df = 3)2 -1.464948  0.231090  1.001124 -1.463    0.143\nns(age, df = 3)3  0.891042  2.437668  0.629382  1.416    0.157\ntrtIntervention   0.090883  1.095141  0.186594  0.487    0.626\nprior            -0.009429  0.990615  0.020175 -0.467    0.640\n\n                 exp(coef) exp(-coef) lower .95 upper .95\nns(age, df = 3)1    1.0404     0.9612   0.53749     2.014\nns(age, df = 3)2    0.2311     4.3273   0.03248     1.644\nns(age, df = 3)3    2.4377     0.4102   0.70998     8.370\ntrtIntervention     1.0951     0.9131   0.75970     1.579\nprior               0.9906     1.0095   0.95221     1.031\n\nConcordance= 0.559  (se = 0.03 )\nLikelihood ratio test= 9  on 5 df,   p=0.1\nWald test            = 9.13  on 5 df,   p=0.1\nScore (logrank) test = 9.34  on 5 df,   p=0.1\n```\n\n\n:::\n:::\n\n\nA multivariable Cox proportional hazards model incorporating a restricted cubic spline transformation of age (df = 3) was fitted to explore potential non-linear effects of age on survival. None of the individual spline terms were statistically significant at the 0.05 level (p = 0.906, 0.143, and 0.157), suggesting that while the spline captures flexibility, the overall contribution of age remains statistically weak.\n\nThe treatment group (p = 0.626) and prior therapy (p = 0.640) also remained non-significant. Model-level tests showed that the likelihood ratio test (p = 0.1), Wald test (p = 0.1), and score test (p = 0.1) were all non-significant, indicating that the model, as specified, may not provide strong explanatory power.\n\nHowever, the model's concordance improved slightly to 0.559 compared to the linear age model, suggesting a modest increase in predictive ability. While not conclusive, the use of splines helps satisfy the functional form assumption and could be valuable if future models identify stronger non-linear trends or interactions with age.\n\n**Checking Proportional Hazards Assumption for Spline Model**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Test proportional hazards assumption for the spline model\ncox.zph(cox_spline)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                chisq df     p\nns(age, df = 3)  4.52  3 0.211\ntrt              2.50  1 0.114\nprior            3.08  1 0.079\nGLOBAL           8.84  5 0.116\n```\n\n\n:::\n:::\n\n\nA Cox proportional hazards model incorporating a restricted cubic spline transformation of age (df = 3) demonstrated acceptable fit to the proportional hazards assumption across all covariates. The global Schoenfeld residuals test was non-significant (p = 0.116), suggesting that the model adequately satisfies the proportional hazards assumption. Individually, spline-transformed age (p = 0.211), treatment group (p = 0.114), and prior treatment (p = 0.079) all showed no significant time-dependent effects.\n\n**Visual Check of Proportional Hazards Assumption for Spline Model**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Visual check of Schoenfeld residuals for spline model\nplot(cox.zph(cox_spline))\n```\n\n::: {.cell-output-display}\n![](veteran-lung-cancer-coxph_files/figure-html/unnamed-chunk-26-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](veteran-lung-cancer-coxph_files/figure-html/unnamed-chunk-26-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](veteran-lung-cancer-coxph_files/figure-html/unnamed-chunk-26-3.png){width=672}\n:::\n:::\n\n\n**Martingale Residuals for Spline Model**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Residuals vs linear predictor\nveteran$martingale_spline <- residuals(cox_spline, type = \"martingale\")\nveteran$linear_pred_spline <- predict(cox_spline, type = \"lp\")\n\nggplot(veteran, aes(x = linear_pred_spline, y = martingale_spline, color = trt)) +\n  geom_point(alpha = 0.6) +\n  geom_hline(yintercept = 0, linetype = \"dashed\", color = \"grey30\") +\n  theme_minimal(base_size = 13) +\n  labs(\n    title = \"Martingale Residuals vs Linear Predictor\\n(Spline Model)\",\n    x = \"Linear Predictor (Log Hazard)\",\n    y = \"Martingale Residual\",\n    color = \"Treatment Group\"\n  ) +\n  scale_color_manual(values = c(\"Control\" = \"#A569BD\", \"Intervention\" = \"#45B39D\")) +\n  theme(plot.title = element_text(hjust = 0.5, face = \"bold\"))\n```\n\n::: {.cell-output-display}\n![](veteran-lung-cancer-coxph_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n:::\n\n\n## Model Comparison: Linear vs Spline Age Term\n\nWe now compare the original multivariable Cox model with age modeled linearly to the updated model using a spline transformation for age. This allows us to formally test whether the added flexibility of the spline significantly improves model fit.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Compare linear age model vs spline-transformed age model\nanova(cox_multivariable, cox_spline, test = \"LRT\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Deviance Table\n Cox model: response is  Surv(time, status)\n Model 1: ~ trt + age + prior\n Model 2: ~ ns(age, df = 3) + trt + prior\n   loglik  Chisq Df Pr(>|Chi|)  \n1 -504.90                       \n2 -500.95 7.9117  2    0.01914 *\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nA likelihood ratio test comparing a model with age modeled linearly to one using restricted cubic splines (df = 3) showed a statistically significant improvement in fit (χ² = 7.91, df = 2, p = 0.019). This suggests that the effect of age on survival is non-linear, and that modeling age with splines better captures its relationship with hazard.\n\n**Visualizing the Effect of Spline-Transformed Age**\n\nThis section uses 'termplot()' to visualize how the hazard changes across age when modeled as a spline. This provides an intuitive look at the non-linear relationship.\n\n::: {.callout-note title=\"Understanding ANOVA in Cox Regression\" collapse=\"true\"}\n\nIn the context of **Cox proportional hazards models**, ANOVA isn't used in the traditional sense (like comparing means). Instead, it's a way of **comparing nested models** using their **log-likelihoods**.\n\nThis is typically done using the **Likelihood Ratio Test (LRT)**, which answers the question:\n\n> _\"Does the more complex model fit significantly better than the simpler one?\"_\n\n### **🔍 What the Output Shows:**\n\n- **Model 1:** The **simpler model** (fewer terms or more constrained terms)\n- **Model 2:** The **more complex model** (extra variables or flexible terms, e.g., splines)\n- **Log-likelihoods:** How well each model fits the data (less negative = better)\n- **Chisq:** Computed as `2 × (LL₂ − LL₁)`  \n- **Degrees of freedom:** Difference in number of parameters\n- **p-value:** Significance of improvement in fit\n\n### **✅ How to Interpret:**\n\n- **p < 0.05** → The complex model fits significantly better → **keep it**\n- **p ≥ 0.05** → No meaningful improvement → **stick with the simpler model**\n\nThis approach is especially useful for:\n- Deciding whether to model continuous variables **non-linearly** (e.g., with splines)\n- Evaluating whether new covariates **add predictive value**\n- Performing **stepwise model refinement**\n\n📦 **Takeaway:**  \nUse ANOVA/LRT in Cox regression to guide decisions about **model complexity vs parsimony**, balancing better fit with interpretability.\n\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntermplot(cox_spline, se = TRUE, col.term = \"blue\")\n```\n\n::: {.cell-output-display}\n![](veteran-lung-cancer-coxph_files/figure-html/unnamed-chunk-29-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](veteran-lung-cancer-coxph_files/figure-html/unnamed-chunk-29-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](veteran-lung-cancer-coxph_files/figure-html/unnamed-chunk-29-3.png){width=672}\n:::\n:::\n\n\nThe term plots from the spline-based Cox model provide a visual assessment of each covariate's partial effect on the log hazard:\n\n    Age (modeled using natural splines with 3 degrees of freedom) shows a non-linear relationship with the log hazard. The plot reveals a shallow U-shaped curve, suggesting a modest protective effect around age 55, with increased hazard at both younger and older extremes. However, the confidence bands are relatively wide, indicating some uncertainty in the effect.\n\n    Treatment Group (trt) appears as two flat lines corresponding to the control and intervention groups. The overlap of the confidence bands with zero implies no statistically significant difference in log hazard between groups.\n\n    Prior Treatment (prior) similarly shows a nearly flat effect line across both levels (0 and 1), with confidence intervals that comfortably include zero. This suggests no strong independent effect of prior treatment on survival.\n\nThese visualizations are consistent with the statistical output, reinforcing the conclusion that age shows the most complex effect, while treatment and prior therapy do not demonstrate significant associations with survival in this model.\n\n::: {.callout-note title=\"How to Interpret Term Plots in Cox Models\" collapse=\"true\"}\n\n**Term plots** visualize the *partial effect* of each covariate in a fitted model while holding other variables constant. They are especially helpful for interpreting transformations like splines.\n\n**🔹 What is a term plot?**  \nA term plot shows how the **log hazard** (on the y-axis) changes with a covariate (on the x-axis), after accounting for all other variables in the model.\n\n- The **blue line** is the estimated partial effect of that variable.\n- The **dashed orange lines** show the 95% confidence interval.\n- The interpretation depends on the type of variable:\n\n**🔸 Continuous Variables (e.g., Age):**\n\n- For **linear terms**, the blue line should be roughly straight.\n- For **splines** or transformed terms:\n  - A *curved* blue line indicates a non-linear relationship.\n  - Areas where the confidence band **does not include 0** suggest a statistically significant effect on the log hazard.\n  - Patterns like U-shapes, inflection points, or steep climbs reveal how risk evolves across the covariate range.\n\n**🔸 Binary Variables (e.g., Treatment, Prior Therapy):**\n\n- These are shown as **two horizontal segments**:\n  - One for each group (e.g., Control = 0, Intervention = 1).\n  - The **difference between the two** shows the log hazard shift due to that variable.\n- If the confidence intervals **include zero**, there's no strong evidence that the variable affects the hazard.\n\n**✅ Best Uses:**\n\n- Confirming that spline-transformed terms behave as expected.\n- Checking if a linear term should be transformed (e.g., age might be better modeled with splines).\n- Double-checking whether binary variables have any meaningful effect.\n\n🧠 _Tip:_ Term plots don't replace statistical tests, but they **visualize model estimates** clearly and intuitively.\n\n:::\n\n\n# 📈 Interaction or Additive Effects?\n# 🧾 Model Summary & Interpretation\n## 📌 Hazard Ratios\n## 🧠 Clinical Interpretation\n# 🧾 Conclusion\n# 📌 Limitations\n\n",
    "supporting": [
      "veteran-lung-cancer-coxph_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}